### ISSUE TITLE
'from unet_models import unet11' reports error

### ISSUE THREAD

**Issue by shawnyuen** [ternaus/TernausNet#1]
Hello, authors,
    Thanks to your sharing code and paper. I read 'Example.ipynb' then implement related codes. When I type 'from unet_models import unet11', I get an error 
'File "unet_models.py", line 16
    def __init__(self, in_: int, out: int):
SyntaxError: invalid syntax'

How can I fix it?
My Pytorch version is 0.1.12.

**Comment by ternaus** [comment]
Adding the type of the arguments to the function is a Python 3 feature. I removed it. Should work now.
