### ISSUE TITLE
training example

### ISSUE THREAD

**Issue by pmcrodrigues** [ternaus/TernausNet#2]
Hello,
Thank you for this upload and congrats on winning the Kaggle challenge. Is it possible for you to provide an example of how to train the network? I can't seem to put everything just right for it to run.

**Comment by ternaus** [comment]
Does this work?

https://github.com/asanakoy/kaggle_carvana_segmentation/blob/master/ternaus/src/train.py

or 

https://github.com/ternaus/robot-surgery-segmentation

**Comment by pmcrodrigues** [comment]
Awesome, I'll check it out. Thanks

**Comment by pmcrodrigues** [comment]
Those work nicely, thanks!
