### ISSUE TITLE
How can I make this code work with images of 3 bands only? 

### ISSUE THREAD

**Issue by alaeddine-abbagh** [ternaus/TernausNet#9]
How can I make this code work with images of 3 bands only?

**Comment by ternaus** [comment]
What do you mean?

The current implementation is using 3 channel images as an input.

**Comment by alaeddine-abbagh** [comment]
In the extra function, it uses the _A, _P and _M version of the image which are in the sixteen band folder. I wanted to use my own image ( say its name is « 1.tiff »), but the error was that it didn’t find the « 1_P.tiff » image. Any help please ?

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Vladimir Iglovikov <notifications@github.com>
Envoyé : Wednesday, August 1, 2018 12:33:52 AM
À : ternaus/TernausNet
Cc : Ivanovicwanheda; Author
Objet : Re: [ternaus/TernausNet] How can I make this code work with images of 3 bands only? (#9)


What do you mean?

The current implementation is using 3 channel images as an input.

**Comment by ternaus** [comment]
Are you referring to this repo https://github.com/ternaus/TernausNetv2 ?

**Comment by alaeddine-abbagh** [comment]
Thank you for your response.
No, I’m referring to this one : https://github.com/ternaus/kaggle_dstl_submission. It didn’t work for my 3 band image.
And please, can you tell me how can I label my own images ? I’ve seen that your labels are in a .h5 file.
Thank you so much, I really appreciate it. I’ve been working on this code for like 2 months to make it work on python 3.6.
Sincerely,
Alaeddine Sabbagh

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Vladimir Iglovikov <notifications@github.com>
Envoyé : Wednesday, August 1, 2018 7:30:13 PM
À : ternaus/TernausNet
Cc : Ivanovicwanheda; Author
Objet : Re: [ternaus/TernausNet] How can I make this code work with images of 3 bands only? (#9)


Are you referring to this repo https://github.com/ternaus/TernausNetv2 ?

**Comment by ternaus** [comment]
If you have 3 band images, and they are in RGB, you can try to adapt this code:

https://github.com/ternaus/robot-surgery-segmentation

It has the whole pipeline for binary segmentation. You just need to update DataLoader to work with the data that you have.

To label your own images you can you tools that are designed for labeling. Say https://supervise.ly works pretty well.

**Comment by alaeddine-abbagh** [comment]
Thank you so much.
Don’t you have any idea about how to do make some changes to the code to make it implimentable with RGB ?  ( https://github.com/ternaus/kaggle_dstl_submission. )
My project is about detecting urbain zones with satellite images using RGB images.
Sincerely,

Alaeddine Sabbagh

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Vladimir Iglovikov <notifications@github.com>
Envoyé : Thursday, August 2, 2018 6:14:33 AM
À : ternaus/TernausNet
Cc : Ivanovicwanheda; Author
Objet : Re: [ternaus/TernausNet] How can I make this code work with images of 3 bands only? (#9)


If you have 3 band images, and they are in RGB, you can try to adapt this code:

https://github.com/ternaus/robot-surgery-segmentation

It has the whole pipeline for binary segmentation. You just need to update DataLoader to work with the data that you have.

To label your own images you can you tools that are designed for labeling. Say https://supervise.ly works pretty well.

**Comment by ternaus** [comment]
https://github.com/ternaus/kaggle_dstl_submission was written in Keras with Theano backend. And Theano is not supported anymore.

Medical Imaging repo, that I mentioned https://github.com/ternaus/robot-surgery-segmentation is much easier to adapt. And from Deep Learning perspective segmentation algorithms work pretty similar on Medical Imagery, Satellite Imagery or any other RGB images.

**Comment by alaeddine-abbagh** [comment]
I made it work with theano, on python 3.6, already. It worked for me on the data availbale by the dstl ( 16 bands) and I’ve been trying to convert it to work on 3 band images, but in vain.
I will try the new code thank you so much 😊


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Vladimir Iglovikov <notifications@github.com>
Envoyé : Thursday, August 2, 2018 7:12:57 PM
À : ternaus/TernausNet
Cc : Ivanovicwanheda; Author
Objet : Re: [ternaus/TernausNet] How can I make this code work with images of 3 bands only? (#9)


https://github.com/ternaus/kaggle_dstl_submission was written in Keras with Theano backend. And Theano is not supported anymore.

Medical Imaging repo, that I mentioned https://github.com/ternaus/robot-surgery-segmentation is much easier to adapt. And from Deep Learning perspective segmentation algorithms work pretty similar on Medical Imagery, Satellite Imagery or any other RGB images.

**Comment by alaeddine-abbagh** [comment]
Greetings,
I get this error while training this code ( https://github.com/ternaus/robot-surgery-segmentation):
UnboundLocalError: local variable 'device_ids' referenced before assignment

May you please give me a hand ? That’s very crucial to my project.
Thank you so much.
Sincerely

Alaeddine Sabbagh, Tunisia Polytechnic School
